apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8095
      targetPort: http
      protocol: TCP
      name: http
    - port: 8097
      targetPort: stream
      protocol: TCP
      name: stream
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  loadBalancerIP: 192.168.1.3
